version: '3.8'

services:
  # =============================================================================
  # DATABASE SERVICES - PostgreSQL for each company (แยก Database + Auth)
  # =============================================================================
  
  postgres-company-a:
    image: postgres:15
    container_name: postgres-company-a
    environment:
      POSTGRES_DB: siamtech_company_a
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_company_a_data:/var/lib/postgresql/data
      - ./init-company-a.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    networks:
      - siamtech_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d siamtech_company_a"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-company-b:
    image: postgres:15
    container_name: postgres-company-b
    environment:
      POSTGRES_DB: siamtech_company_b
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_company_b_data:/var/lib/postgresql/data
      - ./init-company-b.sql:/docker-entrypoint-initdb.d/02-init.sql:ro
    networks:
      - siamtech_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d siamtech_company_b"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-company-c:
    image: postgres:15
    container_name: postgres-company-c
    environment:
      POSTGRES_DB: siamtech_company_c
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5434:5432"
    volumes:
      - postgres_company_c_data:/var/lib/postgresql/data
      - ./init-company-c.sql:/docker-entrypoint-initdb.d/03-init.sql:ro
    networks:
      - siamtech_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d siamtech_company_c"]
      interval: 30s
      timeout: 10s
      retries: 5

  # =============================================================================
  # SHARED INFRASTRUCTURE
  # =============================================================================

  redis:
    image: redis:7-alpine
    container_name: siamtech-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - siamtech_network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # =============================================================================
  # CORE AI SERVICE - RAG with Multi-Model Support
  # =============================================================================

  rag-service:
    build:
      context: .
      dockerfile: Dockerfile.rag
    container_name: siamtech-rag-service
    ports:
      - "5000:5000"
    environment:
      # External Ollama Server
      - OLLAMA_BASE_URL=http://192.168.11.97:12434
      - OLLAMA_TIMEOUT=30
      
      # Multi-tenant Database Configuration
      - POSTGRES_HOST_COMPANY_A=postgres-company-a
      - POSTGRES_PORT_COMPANY_A=5432
      - POSTGRES_DB_COMPANY_A=siamtech_company_a
      - POSTGRES_USER_COMPANY_A=postgres
      - POSTGRES_PASSWORD_COMPANY_A=password123
      
      - POSTGRES_HOST_COMPANY_B=postgres-company-b
      - POSTGRES_PORT_COMPANY_B=5432
      - POSTGRES_DB_COMPANY_B=siamtech_company_b
      - POSTGRES_USER_COMPANY_B=postgres
      - POSTGRES_PASSWORD_COMPANY_B=password123
      
      - POSTGRES_HOST_COMPANY_C=postgres-company-c
      - POSTGRES_PORT_COMPANY_C=5432
      - POSTGRES_DB_COMPANY_C=siamtech_company_c
      - POSTGRES_USER_COMPANY_C=postgres
      - POSTGRES_PASSWORD_COMPANY_C=password123
      
      # Shared Services
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TENANT_CONFIG_FILE=/app/tenant_config.yaml
      - DEFAULT_TENANT=company-a
      
      # Models Configuration (แยกตาม tenant)
      - MODEL_COMPANY_A=llama3.1:8b
      - MODEL_COMPANY_B=llama3.1:8b  
      - MODEL_COMPANY_C=llama3.1:8b
      
      # Debug and Logging
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      
    networks:
      - siamtech_network
    depends_on:
      - postgres-company-a
      - postgres-company-b
      - postgres-company-c
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # =============================================================================
  # N8N WORKFLOW ORCHESTRATOR - Single Workflow, Multi-Tenant Routing
  # =============================================================================

  n8n:
    image: n8nio/n8n:latest
    container_name: siamtech-n8n
    ports:
      - "5678:5678"
    environment:
      # n8n Configuration
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      
      # External Ollama Server
      - OLLAMA_BASE_URL=http://192.168.11.97:12434
      
      # Multi-tenant Database Configuration (for n8n nodes)
      - POSTGRES_HOST_COMPANY_A=postgres-company-a
      - POSTGRES_PORT_COMPANY_A=5432
      - POSTGRES_DB_COMPANY_A=siamtech_company_a
      - POSTGRES_USER_COMPANY_A=postgres
      - POSTGRES_PASSWORD_COMPANY_A=password123
      
      - POSTGRES_HOST_COMPANY_B=postgres-company-b
      - POSTGRES_PORT_COMPANY_B=5432
      - POSTGRES_DB_COMPANY_B=siamtech_company_b
      - POSTGRES_USER_COMPANY_B=postgres
      - POSTGRES_PASSWORD_COMPANY_B=password123
      
      - POSTGRES_HOST_COMPANY_C=postgres-company-c
      - POSTGRES_PORT_COMPANY_C=5432
      - POSTGRES_DB_COMPANY_C=siamtech_company_c
      - POSTGRES_USER_COMPANY_C=postgres
      - POSTGRES_PASSWORD_COMPANY_C=password123
      
      # Models per Tenant
      - MODEL_COMPANY_A=llama3.1:8b
      - MODEL_COMPANY_B=gemma2:9b
      - MODEL_COMPANY_C=phi3:14b
      
      # RAG Service
      - RAG_SERVICE_URL=http://rag-service:5000
      
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - siamtech_network
    depends_on:
      - postgres-company-a
      - postgres-company-b
      - postgres-company-c
      - redis
      - rag-service
    restart: unless-stopped

  # =============================================================================
  # COMPANY A - BANGKOK HQ (llama3.1:8b model)
  # =============================================================================
  
  openwebui-proxy-company-a:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: siamtech-proxy-company-a
    ports:
      - "8011:8001"
    environment:
      - N8N_BASE_URL=http://n8n:5678
      - TENANT_CONFIG_FILE=/app/tenant_config.yaml
      - DEFAULT_TENANT=company-a
      - FORCE_TENANT=company-a 
      - REQUIRE_TENANT_HEADER=false
      - PORT=8001
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      # Model specific for Company A
      - TENANT_MODEL=llama3.1:8b
      - OLLAMA_BASE_URL=http://192.168.11.97:12434
    networks:
      - siamtech_network
    depends_on:
      - n8n
      - rag-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  open-webui-company-a:
    image: ghcr.io/open-webui/open-webui:main
    container_name: siamtech-webui-company-a
    ports:
      - "3000:8080"
    environment:
      - OPENAI_API_BASE_URL=http://openwebui-proxy-company-a:8001/v1
      - OPENAI_API_KEY=sk-company-a-llama31-8b
      - WEBUI_NAME=SiamTech Bangkok HQ - AI Assistant (Llama 3.1 8B)
      - WEBUI_URL=http://localhost:3000
      - DEFAULT_USER_ROLE=user
      - ENABLE_SIGNUP=true
      - SHOW_ADMIN_DETAILS=false
      - WEBUI_DESCRIPTION=AI Assistant สำหรับสำนักงานใหญ่ กรุงเทพมหานคร (ใช้โมเดล Llama 3.1 8B)
      # Theme สำหรับ Company A
      - WEBUI_THEME_COLOR=#667eea
    volumes:
      - open_webui_company_a_data:/app/backend/data
    networks:
      - siamtech_network
    depends_on:
      - openwebui-proxy-company-a
    restart: unless-stopped

  # =============================================================================
  # COMPANY B - CHIANG MAI REGIONAL (gemma2:9b model)
  # =============================================================================
  
  openwebui-proxy-company-b:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: siamtech-proxy-company-b
    ports:
      - "8101:8001"
    environment:
      - N8N_BASE_URL=http://n8n:5678
      - TENANT_CONFIG_FILE=/app/tenant_config.yaml
      - DEFAULT_TENANT=company-b
      - FORCE_TENANT=company-b 
      - REQUIRE_TENANT_HEADER=false
      - PORT=8001
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      # Model specific for Company B
      - TENANT_MODEL=gemma2:9b
      - OLLAMA_BASE_URL=http://192.168.11.97:12434
    networks:
      - siamtech_network
    depends_on:
      - n8n
      - rag-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  open-webui-company-b:
    image: ghcr.io/open-webui/open-webui:main
    container_name: siamtech-webui-company-b
    ports:
      - "3100:8080"
    environment:
      - OPENAI_API_BASE_URL=http://openwebui-proxy-company-b:8001/v1
      - OPENAI_API_KEY=sk-company-b-gemma2-9b
      - WEBUI_NAME=SiamTech Chiang Mai - AI Assistant (Gemma2 9B)
      - WEBUI_URL=http://localhost:3100
      - DEFAULT_USER_ROLE=user
      - ENABLE_SIGNUP=true
      - SHOW_ADMIN_DETAILS=false
      - WEBUI_DESCRIPTION=AI Assistant สำหรับสาขาภาคเหนือ เชียงใหม่ (ใช้โมเดล Gemma2 9B)
      # Theme สำหรับ Company B
      - WEBUI_THEME_COLOR=#f093fb
    volumes:
      - open_webui_company_b_data:/app/backend/data
    networks:
      - siamtech_network
    depends_on:
      - openwebui-proxy-company-b
    restart: unless-stopped

  # =============================================================================
  # COMPANY C - INTERNATIONAL (phi3:14b model)
  # =============================================================================
  
  openwebui-proxy-company-c:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: siamtech-proxy-company-c
    ports:
      - "8201:8001"
    environment:
      - N8N_BASE_URL=http://n8n:5678
      - TENANT_CONFIG_FILE=/app/tenant_config.yaml
      - DEFAULT_TENANT=company-c
      - FORCE_TENANT=company-c
      - REQUIRE_TENANT_HEADER=false
      - PORT=8001
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
      # Model specific for Company C
      - TENANT_MODEL=phi3:14b
      - OLLAMA_BASE_URL=http://192.168.11.97:12434
    networks:
      - siamtech_network
    depends_on:
      - n8n
      - rag-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  open-webui-company-c:
    image: ghcr.io/open-webui/open-webui:main
    container_name: siamtech-webui-company-c
    ports:
      - "3200:8080"
    environment:
      - OPENAI_API_BASE_URL=http://openwebui-proxy-company-c:8001/v1
      - OPENAI_API_KEY=sk-company-c-phi3-14b
      - WEBUI_NAME=SiamTech International - AI Assistant (Phi3 14B)
      - WEBUI_URL=http://localhost:3200
      - DEFAULT_USER_ROLE=user
      - ENABLE_SIGNUP=true
      - SHOW_ADMIN_DETAILS=false
      - WEBUI_DESCRIPTION=AI Assistant for Global Operations (Powered by Phi3 14B)
      # Theme สำหรับ Company C
      - WEBUI_THEME_COLOR=#4facfe
    volumes:
      - open_webui_company_c_data:/app/backend/data
    networks:
      - siamtech_network
    depends_on:
      - openwebui-proxy-company-c
    restart: unless-stopped

  # =============================================================================
  # ADMIN DASHBOARD
  # =============================================================================

  admin-dashboard:
    image: nginx:alpine
    container_name: siamtech-admin-dashboard
    ports:
      - "9000:80"
    volumes:
      - ./admin-dashboard:/usr/share/nginx/html:ro
    networks:
      - siamtech_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  postgres_company_a_data:
    driver: local
  postgres_company_b_data:
    driver: local
  postgres_company_c_data:
    driver: local
  open_webui_company_a_data:
    driver: local
  open_webui_company_b_data:
    driver: local
  open_webui_company_c_data:
    driver: local
  redis_data:
    driver: local
  n8n_data:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  siamtech_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1