# Multi-Tenant Configuration for SiamTech
# แต่ละบริษัทใช้โมเดลต่างกัน + Database แยกกัน

tenants:
  company-a:
    name: "SiamTech Bangkok HQ"
    description: "สำนักงานใหญ่ กรุงเทพมฯ"
    language: "th"
    
    # AI Model Configuration
    ai_model:
      provider: "ollama"
      base_url: "http://13.212.102.46:12434"
      model_name: "llama3.1:8b"  # โมเดลหลักสำหรับ Company A
      temperature: 0.7
      max_tokens: 2000
      context_length: 4096
    
    # Database Configuration
    database:
      host: "postgres-company-a"
      port: 5432
      database: "siamtech_company_a"
      username: "postgres"
      password: "password123"
    
    # Business Context
    business_context:
      industry: "Enterprise Software Development"
      specialization: "Large-scale systems, Banking, E-commerce"
      team_size: 15
      location: "Bangkok, Thailand"
      established: "2022-01-01"
    
    # UI Configuration
    ui:
      theme_color: "#667eea"
      logo_url: "/assets/logo-company-a.png"
      welcome_message: "สวัสดีครับ! ผมคือ AI Assistant ของสำนักงานใหญ่ กรุงเทพฯ"

  company-b:
    name: "SiamTech Chiang Mai Regional"
    description: "สาขาภาคเหนือ เชียงใหม่"
    language: "th"
    
    # AI Model Configuration  
    ai_model:
      provider: "ollama"
      base_url: "http://13.212.102.46:12434"
      model_name: "llama3.1:8b"
      temperature: 0.8
      max_tokens: 1500
      context_length: 3072
    
    # Database Configuration
    database:
      host: "postgres-company-b"
      port: 5432
      database: "siamtech_company_b"
      username: "postgres"
      password: "password123"
    
    # Business Context
    business_context:
      industry: "Tourism & Hospitality Technology"
      specialization: "Tourism systems, Regional projects, Local businesses"
      team_size: 10
      location: "Chiang Mai, Thailand"
      established: "2022-02-01"
    
    # UI Configuration
    ui:
      theme_color: "#f093fb"
      logo_url: "/assets/logo-company-b.png"
      welcome_message: "สวัสดีครับ! ผมคือ AI Assistant ของสาขาเชียงใหม่"

  company-c:
    name: "SiamTech International"
    description: "International Operations"
    language: "en"
    
    # AI Model Configuration
    ai_model:
      provider: "ollama"
      base_url: "http://13.212.102.46:12434"
      model_name: "llama3.1:8b" 
      temperature: 0.6
      max_tokens: 2500
      context_length: 8192
    
    # Database Configuration
    database:
      host: "postgres-company-c"
      port: 5432
      database: "siamtech_company_c"
      username: "postgres"
      password: "password123"
    
    # Business Context
    business_context:
      industry: "Global Software Solutions"
      specialization: "International clients, Cross-border payments, Multi-currency"
      team_size: 8
      location: "Bangkok, Thailand (Global Operations)"
      established: "2022-02-15"
    
    # UI Configuration
    ui:
      theme_color: "#4facfe"
      logo_url: "/assets/logo-company-c.png"
      welcome_message: "Hello! I'm your AI Assistant for SiamTech International operations."

# Global Settings
global_settings:
  # Shared Ollama Server
  ollama_server:
    base_url: "http://13.212.102.46:12434"
    timeout: 30
    retry_attempts: 3
  
  # Available Models (จาก server)
  available_models:
    - "llama3.1:8b"    # Company A
    - "llama3.1:8b"      # Company B  
    - "llama3.1:8b"       # Company C
  
  # Security
  security:
    enable_tenant_isolation: true
    require_authentication: true
    session_timeout: 3600  # 1 hour
  
  # Monitoring
  monitoring:
    enable_metrics: true
    log_level: "INFO"
    track_usage: true